Upgrade to gophercloud 2.0.0
sapcc/gophercloud-sapcc pull request #97
Opened 2024-07-01 13:52 UTC by SuperSandro2000

2024-07-03 12:37 UTC, SuperSandro2000 commented
checks will be fixed when the action is available on master with the updated go version.

2024-07-04 13:15 UTC, kayrus commented
@SuperSandro2000 I'll take care of the interconnections package.

2024-07-08 13:13 UTC, majewsky requested changes
Rest looks good.

2024-07-08 13:13 UTC, majewsky commented on resources/v1/clusters/testing/requests_test.go
> +						Subcapacities: json.RawMessage(`[{"cores":http.StatusOK,"hypervisor":"cluster-1"},{"cores":800,"hypervisor":"cluster-2"}]`),
This is not valid JSON. Run-away regex replacement? :)

2024-07-08 13:36 UTC, majewsky approved these changes

2024-07-08 13:36 UTC, merged